# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/duncan/Working/git/game-of-tides_0.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/duncan/Working/git/game-of-tides_0.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duncan/Working/git/game-of-tides_0.2/CMakeFiles /home/duncan/Working/git/game-of-tides_0.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duncan/Working/git/game-of-tides_0.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OgreApp

# Build rule for target.
OgreApp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OgreApp
.PHONY : OgreApp

# fast build rule for target.
OgreApp/fast:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/build
.PHONY : OgreApp/fast

src/Ogre/AdvancedOgreFramework.o: src/Ogre/AdvancedOgreFramework.cpp.o
.PHONY : src/Ogre/AdvancedOgreFramework.o

# target to build an object file
src/Ogre/AdvancedOgreFramework.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/AdvancedOgreFramework.cpp.o
.PHONY : src/Ogre/AdvancedOgreFramework.cpp.o

src/Ogre/AdvancedOgreFramework.i: src/Ogre/AdvancedOgreFramework.cpp.i
.PHONY : src/Ogre/AdvancedOgreFramework.i

# target to preprocess a source file
src/Ogre/AdvancedOgreFramework.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/AdvancedOgreFramework.cpp.i
.PHONY : src/Ogre/AdvancedOgreFramework.cpp.i

src/Ogre/AdvancedOgreFramework.s: src/Ogre/AdvancedOgreFramework.cpp.s
.PHONY : src/Ogre/AdvancedOgreFramework.s

# target to generate assembly for a file
src/Ogre/AdvancedOgreFramework.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/AdvancedOgreFramework.cpp.s
.PHONY : src/Ogre/AdvancedOgreFramework.cpp.s

src/Ogre/AppStateManager.o: src/Ogre/AppStateManager.cpp.o
.PHONY : src/Ogre/AppStateManager.o

# target to build an object file
src/Ogre/AppStateManager.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/AppStateManager.cpp.o
.PHONY : src/Ogre/AppStateManager.cpp.o

src/Ogre/AppStateManager.i: src/Ogre/AppStateManager.cpp.i
.PHONY : src/Ogre/AppStateManager.i

# target to preprocess a source file
src/Ogre/AppStateManager.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/AppStateManager.cpp.i
.PHONY : src/Ogre/AppStateManager.cpp.i

src/Ogre/AppStateManager.s: src/Ogre/AppStateManager.cpp.s
.PHONY : src/Ogre/AppStateManager.s

# target to generate assembly for a file
src/Ogre/AppStateManager.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/AppStateManager.cpp.s
.PHONY : src/Ogre/AppStateManager.cpp.s

src/Ogre/DemoApp.o: src/Ogre/DemoApp.cpp.o
.PHONY : src/Ogre/DemoApp.o

# target to build an object file
src/Ogre/DemoApp.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/DemoApp.cpp.o
.PHONY : src/Ogre/DemoApp.cpp.o

src/Ogre/DemoApp.i: src/Ogre/DemoApp.cpp.i
.PHONY : src/Ogre/DemoApp.i

# target to preprocess a source file
src/Ogre/DemoApp.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/DemoApp.cpp.i
.PHONY : src/Ogre/DemoApp.cpp.i

src/Ogre/DemoApp.s: src/Ogre/DemoApp.cpp.s
.PHONY : src/Ogre/DemoApp.s

# target to generate assembly for a file
src/Ogre/DemoApp.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/DemoApp.cpp.s
.PHONY : src/Ogre/DemoApp.cpp.s

src/Ogre/GameState.o: src/Ogre/GameState.cpp.o
.PHONY : src/Ogre/GameState.o

# target to build an object file
src/Ogre/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/GameState.cpp.o
.PHONY : src/Ogre/GameState.cpp.o

src/Ogre/GameState.i: src/Ogre/GameState.cpp.i
.PHONY : src/Ogre/GameState.i

# target to preprocess a source file
src/Ogre/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/GameState.cpp.i
.PHONY : src/Ogre/GameState.cpp.i

src/Ogre/GameState.s: src/Ogre/GameState.cpp.s
.PHONY : src/Ogre/GameState.s

# target to generate assembly for a file
src/Ogre/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/GameState.cpp.s
.PHONY : src/Ogre/GameState.cpp.s

src/Ogre/MenuState.o: src/Ogre/MenuState.cpp.o
.PHONY : src/Ogre/MenuState.o

# target to build an object file
src/Ogre/MenuState.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/MenuState.cpp.o
.PHONY : src/Ogre/MenuState.cpp.o

src/Ogre/MenuState.i: src/Ogre/MenuState.cpp.i
.PHONY : src/Ogre/MenuState.i

# target to preprocess a source file
src/Ogre/MenuState.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/MenuState.cpp.i
.PHONY : src/Ogre/MenuState.cpp.i

src/Ogre/MenuState.s: src/Ogre/MenuState.cpp.s
.PHONY : src/Ogre/MenuState.s

# target to generate assembly for a file
src/Ogre/MenuState.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/MenuState.cpp.s
.PHONY : src/Ogre/MenuState.cpp.s

src/Ogre/PauseState.o: src/Ogre/PauseState.cpp.o
.PHONY : src/Ogre/PauseState.o

# target to build an object file
src/Ogre/PauseState.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/PauseState.cpp.o
.PHONY : src/Ogre/PauseState.cpp.o

src/Ogre/PauseState.i: src/Ogre/PauseState.cpp.i
.PHONY : src/Ogre/PauseState.i

# target to preprocess a source file
src/Ogre/PauseState.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/PauseState.cpp.i
.PHONY : src/Ogre/PauseState.cpp.i

src/Ogre/PauseState.s: src/Ogre/PauseState.cpp.s
.PHONY : src/Ogre/PauseState.s

# target to generate assembly for a file
src/Ogre/PauseState.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/PauseState.cpp.s
.PHONY : src/Ogre/PauseState.cpp.s

src/Ogre/main.o: src/Ogre/main.cpp.o
.PHONY : src/Ogre/main.o

# target to build an object file
src/Ogre/main.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/main.cpp.o
.PHONY : src/Ogre/main.cpp.o

src/Ogre/main.i: src/Ogre/main.cpp.i
.PHONY : src/Ogre/main.i

# target to preprocess a source file
src/Ogre/main.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/main.cpp.i
.PHONY : src/Ogre/main.cpp.i

src/Ogre/main.s: src/Ogre/main.cpp.s
.PHONY : src/Ogre/main.s

# target to generate assembly for a file
src/Ogre/main.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Ogre/main.cpp.s
.PHONY : src/Ogre/main.cpp.s

src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.o: src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.o
.PHONY : src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.o

# target to build an object file
src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.o
.PHONY : src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.o

src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.i: src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.i
.PHONY : src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.i

# target to preprocess a source file
src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.i
.PHONY : src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.i

src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.s: src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.s
.PHONY : src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.s

# target to generate assembly for a file
src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.s
.PHONY : src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.cpp.s

src/Voronoi/voronoi.o: src/Voronoi/voronoi.cpp.o
.PHONY : src/Voronoi/voronoi.o

# target to build an object file
src/Voronoi/voronoi.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Voronoi/voronoi.cpp.o
.PHONY : src/Voronoi/voronoi.cpp.o

src/Voronoi/voronoi.i: src/Voronoi/voronoi.cpp.i
.PHONY : src/Voronoi/voronoi.i

# target to preprocess a source file
src/Voronoi/voronoi.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Voronoi/voronoi.cpp.i
.PHONY : src/Voronoi/voronoi.cpp.i

src/Voronoi/voronoi.s: src/Voronoi/voronoi.cpp.s
.PHONY : src/Voronoi/voronoi.s

# target to generate assembly for a file
src/Voronoi/voronoi.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/Voronoi/voronoi.cpp.s
.PHONY : src/Voronoi/voronoi.cpp.s

src/data/data.o: src/data/data.cpp.o
.PHONY : src/data/data.o

# target to build an object file
src/data/data.cpp.o:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/data/data.cpp.o
.PHONY : src/data/data.cpp.o

src/data/data.i: src/data/data.cpp.i
.PHONY : src/data/data.i

# target to preprocess a source file
src/data/data.cpp.i:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/data/data.cpp.i
.PHONY : src/data/data.cpp.i

src/data/data.s: src/data/data.cpp.s
.PHONY : src/data/data.s

# target to generate assembly for a file
src/data/data.cpp.s:
	$(MAKE) -f CMakeFiles/OgreApp.dir/build.make CMakeFiles/OgreApp.dir/src/data/data.cpp.s
.PHONY : src/data/data.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... OgreApp"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/Ogre/AdvancedOgreFramework.o"
	@echo "... src/Ogre/AdvancedOgreFramework.i"
	@echo "... src/Ogre/AdvancedOgreFramework.s"
	@echo "... src/Ogre/AppStateManager.o"
	@echo "... src/Ogre/AppStateManager.i"
	@echo "... src/Ogre/AppStateManager.s"
	@echo "... src/Ogre/DemoApp.o"
	@echo "... src/Ogre/DemoApp.i"
	@echo "... src/Ogre/DemoApp.s"
	@echo "... src/Ogre/GameState.o"
	@echo "... src/Ogre/GameState.i"
	@echo "... src/Ogre/GameState.s"
	@echo "... src/Ogre/MenuState.o"
	@echo "... src/Ogre/MenuState.i"
	@echo "... src/Ogre/MenuState.s"
	@echo "... src/Ogre/PauseState.o"
	@echo "... src/Ogre/PauseState.i"
	@echo "... src/Ogre/PauseState.s"
	@echo "... src/Ogre/main.o"
	@echo "... src/Ogre/main.i"
	@echo "... src/Ogre/main.s"
	@echo "... src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.o"
	@echo "... src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.i"
	@echo "... src/Voronoi/MapManagerLibrary/voronoi/VoronoiDiagramGenerator.s"
	@echo "... src/Voronoi/voronoi.o"
	@echo "... src/Voronoi/voronoi.i"
	@echo "... src/Voronoi/voronoi.s"
	@echo "... src/data/data.o"
	@echo "... src/data/data.i"
	@echo "... src/data/data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

